# ============================================
# Cloud Build - Despliegue automático
# ============================================

steps:
  # Paso 0: Leer variables del .env y exportarlas
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Leer .env y exportar variables (ignorar comentarios y líneas vacías)
        if [ -f .env ]; then
          export $(grep -v '^#' .env | grep -v '^$' | xargs)
        fi
        # Usar valores por defecto si no existen en .env
        export FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-bancamia-dataexpress}
        export FIREBASE_API_KEY=${FIREBASE_API_KEY:-}
        export FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-bancamia-dataexpress.firebaseapp.com}
        export FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-bancamia-dataexpress.firebasestorage.app}
        export FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID:-}
        export FIREBASE_APP_ID=${FIREBASE_APP_ID:-}
        export FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID:-}
        # Guardar todas las variables en archivo para pasarlo al siguiente paso
        {
          echo "FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}"
          echo "FIREBASE_API_KEY=${FIREBASE_API_KEY}"
          echo "FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}"
          echo "FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}"
          echo "FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}"
          echo "FIREBASE_APP_ID=${FIREBASE_APP_ID}"
          echo "FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}"
        } > /workspace/env_vars.txt
        echo "Variables cargadas desde .env"
  
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:latest'
      - '.'
  
  # Paso 2: Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:$SHORT_SHA'
  
  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Cargar variables del archivo
        source /workspace/env_vars.txt
        # IMPORTANTE: Usamos el MISMO proyecto para Google Cloud y Firebase
        # Todas las credenciales vienen del .env (no hardcodeadas)
        # Construir string de variables de entorno
        ENV_VARS="NODE_ENV=production"
        ENV_VARS="${ENV_VARS},FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}"
        if [ ! -z "${FIREBASE_API_KEY}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_API_KEY=${FIREBASE_API_KEY}"
        fi
        if [ ! -z "${FIREBASE_AUTH_DOMAIN}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}"
        fi
        if [ ! -z "${FIREBASE_STORAGE_BUCKET}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}"
        fi
        if [ ! -z "${FIREBASE_MESSAGING_SENDER_ID}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}"
        fi
        if [ ! -z "${FIREBASE_APP_ID}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_APP_ID=${FIREBASE_APP_ID}"
        fi
        if [ ! -z "${FIREBASE_MEASUREMENT_ID}" ]; then
          ENV_VARS="${ENV_VARS},FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}"
        fi
        gcloud run deploy bancamia-dataexpress-api \
          --image=gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:$SHORT_SHA \
          --region=southamerica-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=1Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --timeout=300 \
          --concurrency=80 \
          --service-account=firebase-admin@bancamia-dataexpress.iam.gserviceaccount.com \
          --set-env-vars="${ENV_VARS}" \
          --project=bancamia-dataexpress

images:
  - 'gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:$SHORT_SHA'
  - 'gcr.io/bancamia-dataexpress/bancamia-dataexpress-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY

