# ============================================
# Cloud Build - Despliegue automático
# ============================================

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bancamia-dataexpress-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bancamia-dataexpress-api:latest'
      - '.'
  
  # Paso 2: Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bancamia-dataexpress-api:$SHORT_SHA'
  
  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bancamia-dataexpress-api'
      - '--image=gcr.io/$PROJECT_ID/bancamia-dataexpress-api:$SHORT_SHA'
      - '--region=southamerica-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      - '--service-account=firebase-admin@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=NODE_ENV=production,FIREBASE_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/bancamia-dataexpress-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/bancamia-dataexpress-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY

